### ISSUE TITLE
Should the asset base path be auto-created?

### ISSUE THREAD

**Issue by KnightYoshi** [yiisoft/assets#1]
When Yii copies/symlinks files into the asset base path _webroot/assets_ if the directory doesn't exist it throws an error. Shouldn't Yii create the base path if it doesn't exist? 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      |  7
| Operating system | Mac/Linux

**Comment by terabytesoftw** [comment]
The asset manager checks the $ basePath if it does not exist throws an InvalidConfigException, when knowing a route is not correct and when we must create it, then the most logical thing is if the route does not exist should throw an exception.

**Comment by KnightYoshi** [comment]
@terabytesoftw I disagree. The assets directory contents is generated by Yii. I don’t see anything wrong with Yii generating the base assets directory if it doesn’t exist as well.

Prime example. You don’t commit the assets directory contents to the source control. So the assets directory isn’t committed. Then it doesn’t exist when it’s cloned and/or deployed to a server. The application breaks, because a Yii-managed directory isn’t generated by Yii if it doesn’t exist.

**Comment by xepozz** [comment]
@KnightYoshi you can create "base" folder then put inside it `.gitkeep` file and commit it.

**Comment by KnightYoshi** [comment]
@xepozz You can do that, yes, but that is also just a work around. It shouldn't be necessary. The assets directory is managed by Yii, so if it doesn't exist Yii should attempt to create it.

**Comment by samdark** [comment]
I think we can just create it. Nothing's wrong with it.

**Comment by samdark** [comment]
Seems to be fixed in master.
