### ISSUE TITLE
AssetManager load empty AssetBundle when register wrong namespace bundle

### ISSUE THREAD

**Issue by g-rodigy** [yiisoft/assets#123]
### What steps will reproduce the problem?
In view files when load asset with wrong namespace.
````php
// @var Yiisoft\Assets\AssetManager $assetManager
$assetManager->register(\wrong\namespace\AppAsset::class);
````
It happening here `loadBundle()  --->  AssetUtil::createAsset()`
https://github.com/yiisoft/assets/blob/4.0.0/src/AssetLoader.php#L102
https://github.com/yiisoft/assets/blob/4.0.0/src/AssetUtil.php#L44
### What is the expected result?
Expected throw exception
### What do you get instead?
Got empty instance of `AssetBundle`

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 4.0.0
| PHP version      | 8.0
| Operating system |

**Comment by terabytesoftw** [comment]
@g-rodigy I could try this solution thanks, it should work, now the `register()` and `registerMany()` methods throw an exception if the class does not exist, instead with `registerCustomized()`, it supports virtual namespaces.
