### ISSUE TITLE
Move default config to common and add an option to disable publisher on fly

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/assets#132]
Good afternoon, everyone. The documentation describes an example of how to resolve assets from a console command. But - this example does not work without a thorough edit of the configuration, because all dependencies are described in relation to the web. Is it possible to move these dependencies to common and add possibility to switch off publisher at will (add possibility to set it to null in a method). Thanks in advance

**Comment by vjik** [comment]
Seems, you are right. We need move configuration from `di-web` to `di`.

As for disabling the publisher, we can do something like this:

1) Add to params:

```php
    'yiisoft/assets' => [
        // ...
        'assetManager' => [
            'publisher' => AssetPublisherInterface::class, // by default use it
            // ...
        ],
```

2) Use this code in container configuration:

```php
if ($params['yiisoft/assets']['assetManager']['publisher'] !== null) {
    $assetManager = $assetManager->withPublisher(
        $container->get($params['yiisoft/assets']['assetManager']['publisher'])
    );
};
```

3) In app for disable publisher set parameter `'yiisoft/assets' / 'assetManager' / 'publisher'` to null.
