### ISSUE TITLE
Enhancement check recursive filetime.

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/assets#17]
### What steps will reproduce the problem?
Design problem that does not verify the filetime change of the files in the sourcePath directory.

### What is the expected result?
After change sources Its should update css file.

### Additional info
Issues: https://github.com/yiisoft/yii2/issues/17620, https://github.com/yiisoft/yii2/issues/8197

### Solution
I believe that we can implement the craft solution @brandonkelly https://github.com/yiisoft/yii2/issues/8197#issuecomment-279419498 , which is proven to work in craft, in terms of performance, today almost all accommodations are cloud with ssd support, also use the latest PHP version which is the fastest, i believe that performance would not be affected.

Additionally we can eliminate the `forceCopy()` options, and create isCheckFileRecursive, and its behavior would be true, we do the recursive check, in case we are developing, and in case we are in production we change it to false eliminating said check, since the ccs files sourcePath would not change, just checking the directory's filetime as it is right now.

| Q                | A
| ---------------- | ---
| Version          | 3.0
| PHP version      | 7.4
| Operating system | Centos 8

**Comment by terabytesoftw** [comment]
If we apply this improvement that you think of removing `forceCopy()`, and adding in `assetPublisher::class` a new `isCheckFileRecursive property`, which indicates whether or not we should enable recursive checking, so if your assets are not going to change you can disable.

**Comment by samdark** [comment]
Yes, great idea.
