### ISSUE TITLE
Consider using configs instead of asset bundle classes

### ISSUE THREAD

**Issue by samdark** [yiisoft/assets#24]
## Why?

Asset classes are now separated from asset files.

## How

1. Declare assets in config.
2. Register by name, don't use classes.

```php
// config
return [
 'assetName' => [
   'baseUrl' => '',
   ....
 ],
 ....
];

// view
$view->registerAsset('assetName');
```
## Advantages

- Simple.
- Declarative.
- Can merge configs.

## Disadvantages

IDE won't be able to analyze them.

**Comment by samdark** [comment]
Alternative approach by @yiiliveext:

1. Have an empty asset class.
2. Configure it via config.

**Comment by viktorprogger** [comment]
Didn't understand the point "1. Create AssetBundle". Could you explain please?
As I see we can pass the config as a parameter to a default bundle class, and then call `$bundle->register('asset-name');`.

**Comment by samdark** [comment]
@viktorprogger that is creating a class that extends AssetBundle.

**Comment by terabytesoftw** [comment]
> Alternative approach by @yiiliveext:
> 
> 1. Have an empty asset class.
> 2. Configure it via config.
> 
> ## Advantages
> * Flexible. Configs could be merged.
> * Easy to theme.
> * Works with IDE.
> 
> ## Disadvantages
> The process of creating a bundle becomes a bit more complicated:
> 
> Before:
> 
> 1. Create AssetBundle and configure it in the class.
> 2. Register it in a view or config.
> 
> The process after:
> 
> 1. Create AssetBundle.
> 2. Configure asset bundle via config.
> 3. Register it in a view or config.

that can already be done:

```php
    public function testBaseUrlEmptyStringChain(): void
    {
        $this->assetManager->setBundles(
            [
                RootAsset::class => [
                    'depends' => [BaseAsset::class]
                ],
                BaseAsset::class => [
                    'baseUrl' => null,
                ],
            ]
        );
    }
```

**Comment by armpogart** [comment]
I'm for any approach that will allow to detect all asset bundles during the application build and not runtime. This will allow publishing assets during the build, useful when building separate container (docker) for web server and php application and cloud environments, where you usually publish assets to cdn, See also [yiisoft/yii2 issue](https://github.com/yiisoft/yii2/issues/14325)

**Comment by samdark** [comment]
There are multiple approaches for it:

1. There could be a command that scans for asset bundles under directories configured and writes config for further assembly during build time.
2. We can suggest creating such config manually while still using asset bundles. Will need to think about priorities.
3. We can remove asset bundles concept and use configs only. That potentially complicates it about third party asset bundles provided by packages.

**Comment by samdark** [comment]
Yes. With composer-config-plugin the package may do it for you but you'll have way less control then.

**Comment by samdark** [comment]
Decided that there will be a interface separation allowing config-export but bundles will be still there/
