### ISSUE TITLE
Asset Converter options quoted incorrectly

### ISSUE THREAD

**Issue by Thoulah** [yiisoft/assets#25]
### What steps will reproduce the problem?
```
    public ?string $basePath = '@assets';
    public ?string $baseUrl = '@assetsUrl';
    public ?string $sourcePath = '@resources/assets/css';

    public array $css = [
        'site.scss',
    ];

    public array $converterOptions = [
        'scss' => '-I /path/to/bootstrap/scss',
    ];
```

### What is the expected result?
`sass -I /path/to/bootstrap/scss '/path/to/assets/ce37712/site.scss' '/path/to/assets/ce37712/site.css'`

Testing this on the command line works and css is created.

### What do you get instead?
`sass '-I /path/to/bootstrap/scss' '/path/to/assets/ce37712/site.scss' '/path/to/assets/ce37712/site.css'`

Testing this on the command line leads to errors:
```
Error: File to import not found or unreadable: functions.
       Load path: /path/to/bootstrap/scss/ /path/to/bootstrap/scss
        on line 1 of /path/to/assets/ce37712/bootstrap.scss
        from line 8 of /path/to/assets/ce37712/site.scss
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | current dev
| PHP version      | 7.4.6
| Operating system | Debian 9

**Comment by terabytesoftw** [comment]
Your config its wrong:

```php
public array $converterOptions = [
    'sass'   => '--style = -I',
];
```

**Comment by Thoulah** [comment]
Ehh... no.

```
-I, --load-path PATH             Specify a Sass import path.
-t, --style NAME                 Output style. Can be nested (default), compact, compressed, or expanded.
```

**Comment by terabytesoftw** [comment]
The path is specified in sourcePath.

```php
class BootstrapAsset extends AssetBundle
{
    public ?string $basePath = '@assets';

    public ?string $baseUrl = '@assetsUrl';

    public ?string $sourcePath = '@npm/bootstrap';

    public array $css = [
        'scss/bootstrap.scss',
    ];

    public array $converterOptions = [
        'scss' => '--style = compressed',
    ];

    public array $depends = [
        \App\Assets\JqueryAsset::class,
        \App\Assets\PopperAsset::class,
    ];

    public array $publishOptions = [
        'only' => [
            'scss/*',
            'scss/mixins/*',
            'scss/utilities/*',
            'scss/vendor/*'
        ],
    ];
}
```

**Comment by Thoulah** [comment]
I am using `$sourcePath` correctly as it is in my example code, as I am using my own .scss file. With the `'-I` option I pull in the bootstrap scss path to compile my own file combined with their code. The only thing blocking this are the quotes around the options.

**Comment by terabytesoftw** [comment]
tests:

public array $converterOptions = [
    'scss' => '--style = -I /path/to/bootstrap/scss',
];

**Comment by Thoulah** [comment]
Why are you so focused on `--style = `? That is a different sass option that I currently don't want to use and the way you want to use it does not make sense.

**Comment by terabytesoftw** [comment]
```
<?php

declare(strict_types=1);

namespace App\Asset;

use Yiisoft\Assets\AssetBundle;

class BootstrapAsset extends AssetBundle
{
    public ?string $basePath = '@assets';
    public ?string $baseUrl = '@assetsUrl';
    public ?string $sourcePath = '@npm/bootstrap';

    public array $css = [
        'scss/bootstrap.scss',
    ];

    public function __construct()
    {
        $this->converterOptions = [
            'scss' => '-I' . dirname(__dir__,2) . '/resources/css/example.scss'
        ];
    }
}

Please check work for me.
```

**Comment by Thoulah** [comment]
I will try, but that is not a path you are trying to use in `-I, --load-path` as I already suspect why it should fail.

**Comment by Thoulah** [comment]
A little tweaking here and there to make it work. At least no error, but also not a .css file in @assets.
Anyway, as far I can see is the best your code that do to compile bootstrap _without any modifications_ from local example.scss.

**Comment by terabytesoftw** [comment]
update example sorry.

**Comment by Thoulah** [comment]
Haha, take your jacket ;)

I changed the line to `'scss' => '-I ' . dirname(__dir__,2) . '/node_modules/bootstrap/scss'` as it needs a path, not a file:
```
2020-06-11 14:59:17.191900 [error][application] AssetConverter command 'sass '-I /yii3/node_modules/bootstrap/scss' '/yii3/assets/fcc3317c/site.scss' '/yii3/assets/fcc3317c/site.css'' failed with exit code 65:
STDOUT:

STDERR:
Error: File to import not found or unreadable: functions.
       Load path: /yii3/assets/fcc3317c/ /yii3/node_modules/bootstrap/scss
        on line 1 of /yii3/assets/fcc3317c/bootstrap.scss
        from line 8 of /yii3/assets/fcc3317c/site.scss
  Use --trace for backtrace.
```

Copying that command, run in linux console: same error. Removing the quotes from the options: no error. It just won't work with the quotes.

**Comment by Thoulah** [comment]
Now try changing your code `@import "../../../node_modules/bootstrap/scss/bootstrap";` to `@import bootstrap;`

**Comment by terabytesoftw** [comment]
Above you can see the steps it works perfectly, the `AssetConverter::class` is not a SASS cli, but it allows you to work with the most basic options, if you need a more complex construction you should use the cli tool.

**Comment by Thoulah** [comment]
If only works because of your hack. But now try the following with your own example.
- Remove the __construct we tested before
- Add from documentation
  ```php
      public array $converterOptions = [
          'scss' => '--style compressed',
      ];
  ```

  ```
  2020-06-11 15:30:57.640400 [error][application] AssetConverter command 'sass '--style 
  compressed' '/var/www/vhosts/mr42.me/yii3/assets/bf076425/site.scss' 
  '/var/www/vhosts/mr42.me/yii3/assets/bf076425/site.css'' failed with exit code 1:
  STDOUT:

  STDERR:
  OptionParser::InvalidOption: invalid option: --style compressed
    Use --trace for backtrace.
  ```

- Take that command from the error and run it on your console.
- Take that command from the error, remove the quotes from around the options and run it on your console.
