### ISSUE TITLE
Asset with CDN links does not work correct

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/assets#53]
### What steps will reproduce the problem?
Create asset class and render it.

```php
<?php

use Yiisoft\Assets\AssetBundle;

final class CdnFontAwesomeAsset extends AssetBundle
{
    public bool $cdn = true;
    public array $css = [
        'https://use.fontawesome.com/releases/v5.13.0/css/all.css'
    ];
}
```
### What is the expected result?

Link to `use.fontawesome.com` in css styles list:
`https://use.fontawesome.com/releases/v5.13.0/css/all.css`

### What do you get instead?

Link with my domain name prefix:
`https://my.site/https://use.fontawesome.com/releases/v5.13.0/css/all.css`

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by aphraoh** [comment]
Bug in AssetPublisher.php line 183 which is this

        if ($bundle->cdn) {
            **return $this->baseUrl . '/' . $assetPath;**
        }

but should be this because cdn does not need to be prefixed with anything

        if ($bundle->cdn) {
            **return $assetPath;**
        }
