### ISSUE TITLE
Think about how to get away implicit dependency on yiisoft/view

### ISSUE THREAD

**Issue by vjik** [yiisoft/assets#77]
Suggestion by @devanych:

I don't like that we have an implicit dependency on yiisoft/view. Namely, by positions (WebView:: POSITION_HEAD, WebView::POSITION_END , etc.). Need to think about how to get away from this. For example, move these constants to the yiisoft/html package.

**Comment by samdark** [comment]
I think that's alright as it is now. These values depend on the view implementation used and it's not necessary *this* set of values.
