### ISSUE TITLE
AssetManager problem in cloud platform

### ISSUE THREAD

**Issue by kamarton** [yiisoft/assets#8]
### What steps will reproduce the problem?

Yii2 asset manager specified to any file storage and file serving. There is a small problem with this in a cloud platform.

```
  server A          server B            server C   ....     server X
     |                 |                   |                   |
     \---------------------------------------------------------/
                                |
                               LB
                                |
                          client browser
```

Yii2 schema:
1. client make request
2. server A
3. asset managerer copy or symlink files on server A
4. response
5. client make new request with asset urls
6. server B, C (LB select random servers)
7. not found asset files (onlye copy files server A)

Idea:
- It would be nice to have an easy-to-implement solution to not direct file serving.
- serving asset contents
  - from action (read files from direct path, without copy to asset folder)
  - support CDN PUT or another storage (redis, database)

### What is the expected result?

files serving any servers

### What do you get instead?

not found asset files (onlye copy files server A)

### Additional info

yii2 solution (with my source codes):
1. asset manager put base directory to databse
2. asset serving action
3. get base directory from database
4. read and serving content from base directory + url path (with file checks and more)

| Q                | A
| ---------------- | ---
| Version          | 2.x
| PHP version      |  -
| Operating system | -

**Comment by agussuhartono** [comment]
> 
> ### What steps will reproduce the problem?
> 
> Yii2 asset manager specified to any file storage and file serving. There is a small problem with this in a cloud platform.
> 
> ```
>   server A          server B            server C   ....     server X
>      |                 |                   |                   |
>      \---------------------------------------------------------/
>                                 |
>                                LB
>                                 |
>                           client browser
> ```
> 
> Yii2 schema:
> 
>     1. client make request
> 
>     2. server A
> 
>     3. asset managerer copy or symlink files on server A
> 
>     4. response
> 
>     5. client make new request with asset urls
> 
>     6. server B, C (LB select random servers)
> 
>     7. not found asset files (onlye copy files server A)
> 
> 
> Idea:
> 
>     * It would be nice to have an easy-to-implement solution to not direct file serving.
> 
>     * serving asset contents
>       
>       * from action (read files from direct path, without copy to asset folder)
>       * support CDN PUT or another storage (redis, database)
> 
> 
> ### What is the expected result?
> 
> files serving any servers
> ### What do you get instead?
> 
> not found asset files (onlye copy files server A)
> ### Additional info
> 
> yii2 solution (with my source codes):
> 
>     1. asset manager put base directory to databse
> 
>     2. asset serving action
> 
>     3. get base directory from database
> 
>     4. read and serving content from base directory + url path (with file checks and more)
> 
> 
> Q 	A
> Version 	2.x
> PHP version 	-
> Operating system 	-

I think "Yii Asset Manager" on "each server" regenerate assets when first time access

**Comment by samdark** [comment]
This is valid and serious problem that could be solved in multiple ways @SamMousa and @mikk150 suggested:

1. By sharing assets by writing them somewhere else like CDN or S3 bucket using https://github.com/yiisoft/yii-filesystem
2. By pre-collecting assets and publishing these during deployment. In this case we need to ensure that all servers have assets at the same path.
3. By pre-collecting assets and publishing these during development. Ready assets are then deployed to the servers.

Related https://github.com/yiisoft/assets/issues/24 may greatly simplify asset list assembly for 2 and 3.

**Comment by SamMousa** [comment]
I think for the future we should do pre publishing. Moving to containers and immutable deploy artifacts is always safer. Even when wanting to deploy assets to a cdn doing so in advance is better.

**Comment by kamarton** [comment]
> This is valid and serious problem that could be solved in multiple ways @SamMousa and @mikk150 suggested:

I like the idea.

> By pre-collecting assets and publishing these during deployment. In this case we need to ensure that all servers have assets at the same path.

An interesting question here is whether it is always known in advance or not the path. Forces the deploy to receive a different route (path) from the previous state in each case.

For example, if the asset files of one package have not changed for 2 years, it will destroy the CDN function in an intensive development status by e.g. forces downloads to mobile devices up to several times a day.
This may not be a problem in the process, but developers need a guide in this area, otherwise they may run into this problem more easily.

**Comment by SamMousa** [comment]
> For example, if the asset files of one package have not changed for 2 years, it will destroy the CDN function in an intensive development status by e.g. forces downloads to mobile devices up to several times a day.
This may not be a problem in the process, but developers need a guide in this area, otherwise they may run into this problem more easily.

You could still use the file hash as input for path generation, doing it in advance is no different from doing it at runtime..

**Comment by samdark** [comment]
I've recently wrote down about how to solve it in Yii 2: https://rmcreative.ru/blog/post/yii-2-za-balansirovschikom-nagruzki It is in Russian but may be relevant.

**Comment by samdark** [comment]
Seems to be possible with current master. Need to document it.

**Comment by samdark** [comment]
This one is now solved. An example added to readme.
