### ISSUE TITLE
Allow use string as first argument of method `AssetManager::register()`

### ISSUE THREAD

**Issue by vjik** [yiisoft/assets#87]
https://github.com/yiisoft/assets/blob/a31b8e989fd9740bcf1cf9bbd413e856ec00c85a/src/AssetManager.php#L249

Often this method used only for one asset:

```php
$assetManager->register([MainAsset::class]);
```

We can allow use `string` or `string[]`. In this case using the method will be more convenient:

```php
$assetManager->register(MainAsset::class);
```

And for several assets, we can use it as now:

```php
$assetManager->register([Asset1::class, Asset2::class]);
```

**Comment by samdark** [comment]
Decided to make current method to accept one asset. Another method should be created accepting many at the same time.
