### ISSUE TITLE
AssetManager appendTimestamp problem

### ISSUE THREAD

**Issue by kamarton** [yiisoft/assets#9]
### What steps will reproduce the problem?

workflow:
1. asset manager generate URL (`https://www.yiiframework.com/assets/263ed6ff/css/all.min.css?v=1567695980`)
2. CDN (transparent)
3. response send to client
4. `all.min.css` has image reference (`../image/new-image-in-old-name.png`)
5. `https://www.yiiframework.com/assets/263ed6ff/image/new-image-in-old-name.png`
6. not append timestamp and any version
7. CDN deliver old version of image

In addition, there are CDN options that store the content completely without considering the query parameter.

```
server  <---> CDN <---> client
```

### What is the expected result?

The CDN gets a URL that changes from the previous version.

### What do you get instead?

CDN serves the previous content.

### Additional info

There are other problems with `appendTimestamp`:
- file operations are often slow on network drives (In some respects, including the cloud platform.)
- In some cases, the file time represents only the date of the last install and not the actual change in content.
- PHP may not have access to the file.

### Suggest

I suggest add version config.

```php
[
  'assetManager' => [
    'defaultVersion'=> '0.1.0' // or custom string; default version string, if not set
  ],
]

MyAsset extends AssetBundle {
  public $version = '0.3.4'     // override version
}
```

Generated asset URL
```url
https://www.yiiframework.com/assets/263ed6ff/<version>/css/all.min.css

https://www.yiiframework.com/assets/263ed6ff/0.3.4/css/all.min.css
https://www.yiiframework.com/assets/263ed6ff/0.3.4/image/new-image-in-old-name.png
```

| Q                | A
| ---------------- | ---
| Version          | 2.x
| PHP version      | -
| Operating system | -

**Comment by terabytesoftw** [comment]
What would be the best way to solve this problem, the asset manager generates a hash, which is reflected in the directory, appendTimeStamp only works for the files that we define in the assetbundle,  creating another directory does not look very practical, we would have one with the hash and another with the version, and if the version is part of the hash or know what version it is?

**Comment by samdark** [comment]
@terabytesoftw directory hash and timestamp solve different problems:

1. timestamp is there to force a browser ignore its cached content and load new content from a file.
2. hash check is there so fresh files are copied from source to destination.
